In [1]:
import pandas as pd
import statsmodels.formula.api as smf

In [2]:
# Read Low-cost Airline Data
try:
    data_lowcost = pd.read_csv('low_cost_robust.csv', encoding='utf-8')
except UnicodeDecodeError:
    data_lowcost = pd.read_csv('low_cost_robust.csv', encoding='ISO-8859-1')
    
data_lowcost.head()

,status,aircraft,travel_type,travel_class,route,date,seating_comfort,staff_service,food_quality,entertainment,...,value_for_money,recommended,overall_rating,review,watson_sentiment,watson_score,covid_19,company_age,log_company_size,log_net_profit
0,Not Verified,NaN,Business,Economy Class,London Gatwick to Bordeaux,24-Jun,2.0,2.0,NaN,NaN,...,1,no,1,Had not flown EasyJet for over a year because...,negative,-0.850861,0,29,8.552367,5.783825
1,Not Verified,A320,Business,Economy Class,Bristol to Edinburgh,24-May,1.0,1.0,NaN,NaN,...,1,no,1,Given the basic fare cost with no hold bagg...,negative,-0.806221,0,29,8.552367,5.783825
2,? Trip Verified,A320NEO,Solo Leisure,Economy Class,Porto to Ajaccio via Geneva,24-May,3.0,4.0,NaN,NaN,...,5,yes,7,My EasyJet flights from Oporto to Ajaccio wer...,negative,-0.384695,0,29,8.552367,5.783825
3,Not Verified,A320,Couple Leisure,Economy Class,Gatwick to Tenerife,24-May,2.0,5.0,NaN,2.0,...,2,no,2,? ?EasyJet are scammers. We were never informe...,negative,-0.618626,0,29,8.552367,5.783825
4,? Trip Verified,NaN,Solo Leisure,Economy Class,Hurghada to Gatwick,24-May,1.0,1.0,1.0,1.0,...,1,no,3,"I have been travelling for 5 years, between ...",negative,-0.724085,0,29,8.552367,5.783825

In [4]:
#Linear regression analysisï¼š Low-cost 
#covid_19+company_age+log_company_size+log_net_profit
model = smf.ols(formula='watson_score~seating_comfort+staff_service+ground_service+value_for_money+covid_19+company_age+log_company_size+log_net_profit', data=data_lowcost)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           watson_score   R-squared:                       0.643
Model:                            OLS   Adj. R-squared:                  0.642
Method:                 Least Squares   F-statistic:                     509.5
Date:                Tue, 20 Aug 2024   Prob (F-statistic):               0.00
Time:                        05:35:49   Log-Likelihood:                -758.94
No. Observations:                2273   AIC:                             1536.
Df Residuals:                    2264   BIC:                             1587.
Df Model:                           8
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           -1.4482      0.124    -11.641      0.000      -1.692      -1.204
seating_comfort      0.0508      0.009      5.634      0.000       0.033       0.068
staff_service        0.0381      0.008      4.957      0.000       0.023       0.053
ground_service       0.1701      0.009     19.227      0.000       0.153       0.187
value_for_money      0.0824      0.009      9.510      0.000       0.065       0.099
covid_19            -0.0179      0.032     -0.557      0.578      -0.081       0.045
company_age         -0.0015      0.001     -1.243      0.214      -0.004       0.001
log_company_size     0.0365      0.017      2.196      0.028       0.004       0.069
log_net_profit      -0.0018      0.003     -0.572      0.568      -0.008       0.004
==============================================================================
Omnibus:                      132.838   Durbin-Watson:                   1.985
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              480.914
Skew:                           0.169   Prob(JB):                    3.72e-105
Kurtosis:                       5.228   Cond. No.                         521.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [5]:
#Read Traditional Airline Data
try:
    data_traditional = pd.read_csv('traditional_robust.csv', encoding='utf-8')
except UnicodeDecodeError:
    data_traditional = pd.read_csv('traditional_robust.csv', encoding='ISO-8859-1')
    
data_traditional.head()

,status,aircraft,travel_type,travel_class,route,date,seating_comfort,staff_service,food_quality,entertainment,...,value_for_money,recommended,overall_rating,review,watson_sentiment,watson_score,covid_19,company_age,log_company_size,log_net_profit
0,? Trip Verified,Boeing 777,Family Leisure,Premium Economy,Paris to Toronto,24-Jul,2.0,1.0,1.0,1.0,...,3,no,5,Disappointing Premium Economy onboard experi...,negative,-0.679261,0,91,9.826499,6.990257
1,? Trip Verified,NaN,Solo Leisure,Economy Class,New York to Paris,24-Jan,1.0,1.0,NaN,NaN,...,1,no,1,I am very disappointed with this airline and ...,negative,-0.859648,0,91,9.826499,6.990257
2,? Trip Verified,NaN,Solo Leisure,Economy Class,Hamburg to Singapore via Paris,24-Jul,1.0,1.0,NaN,NaN,...,1,no,1,They delay the first flight and the second f...,negative,-0.882312,0,91,9.826499,6.990257
3,? Trip Verified,A321 / Boeing 777-300ER,Couple Leisure,Economy Class,Lisbon to Singapore via Paris,24-Jul,4.0,2.0,2.0,3.0,...,3,no,5,"Boarding was delayed on the first leg, and o...",negative,-0.737017,0,91,9.826499,6.990257
4,? Trip Verified,NaN,Family Leisure,Economy Class,Los Angeles to Barcelona via Paris,24-Jul,3.0,2.0,3.0,2.0,...,1,no,3,"My family of 4 and I are long-time, loyal De...",negative,-0.752723,0,91,9.826499,6.990257

In [6]:
#Linear regression analysis: traditional 
#covid_19+company_age+log_company_size+log_net_profit
model_2 = smf.ols(formula='watson_score~seating_comfort+staff_service+ground_service+value_for_money+covid_19+company_age+log_company_size+log_net_profit', data=data_traditional)
results = model_2.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           watson_score   R-squared:                       0.657
Model:                            OLS   Adj. R-squared:                  0.656
Method:                 Least Squares   F-statistic:                     535.7
Date:                Tue, 20 Aug 2024   Prob (F-statistic):               0.00
Time:                        05:35:58   Log-Likelihood:                -935.08
No. Observations:                2245   AIC:                             1888.
Df Residuals:                    2236   BIC:                             1940.
Df Model:                           8
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           -0.8225      0.167     -4.932      0.000      -1.150      -0.495
seating_comfort      0.0435      0.008      5.383      0.000       0.028       0.059
staff_service        0.0580      0.007      8.063      0.000       0.044       0.072
ground_service       0.0967      0.008     12.840      0.000       0.082       0.111
value_for_money      0.1870      0.009     20.896      0.000       0.169       0.205
covid_19            -0.0375      0.019     -1.974      0.048      -0.075      -0.000
company_age          0.0017      0.001      2.911      0.004       0.001       0.003
log_company_size    -0.0647      0.019     -3.415      0.001      -0.102      -0.028
log_net_profit       0.0030      0.002      1.421      0.156      -0.001       0.007
==============================================================================
Omnibus:                       70.179   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              182.365
Skew:                           0.025   Prob(JB):                     2.51e-40
Kurtosis:                       4.395   Cond. No.                     1.45e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+03. This might indicate that there are
strong multicollinearity or other numerical problems.